from app.repositories.welder_repository import WelderRepository
from app.repositories.welder_certification_repository import WelderCertificationRepository
from app.repositories.welder_ndt_repository import WelderNDTRepository
from app.repositories.user_repository import UserRepository